import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "@/app/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import { Providers } from "./lib/providers";

import { Header } from "./components/layout/header/header";

const NotoSansJapanese = Noto_Sans_JP({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansJapanese.variable} antialiased bg-[#F0F0F0]`}>
        <Providers>
          <Header />
          <div className="w-[84vw] h-[calc(100svh-100px)] mt-[100px] mx-[8vw] bg-white shadow-xl">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
